spring:
  application:
    name: aluno
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aluno
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
